"""Adiciona colunas nome_turma e qtd_alunos na tabela Turmas

Revision ID: 0e394d611c0a
Revises: 470e98369a1e
Create Date: 2024-10-30 15:33:51.349987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e394d611c0a'
down_revision = '470e98369a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ano', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
