"""Adicionar email e telefone ao modelo Aluno

Revision ID: 13bcb54fbf11
Revises: b3d43febf470
Create Date: 2024-10-30 01:54:21.311463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bcb54fbf11'
down_revision = 'b3d43febf470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
