"""Adiciona coluna descricao à tabela turma

Revision ID: 3e57ae25bac6
Revises: 56fe5acbd99d
Create Date: 2024-10-31 01:57:55.163408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e57ae25bac6'
down_revision = '56fe5acbd99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.drop_column('qtd_alunos')
        batch_op.drop_column('nome_turma')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_turma', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('qtd_alunos', sa.INTEGER(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
