"""Add idade and materia to Professor

Revision ID: 470e98369a1e
Revises: 13bcb54fbf11
Create Date: 2024-10-30 02:53:54.800878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470e98369a1e'
down_revision = '13bcb54fbf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('materia', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('materia')
        batch_op.drop_column('idade')

    # ### end Alembic commands ###
