"""Remove a coluna qtd_alunos e nome_turma da tabela Turma

Revision ID: 56fe5acbd99d
Revises: 0e394d611c0a
Create Date: 2024-10-31 01:34:54.549573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fe5acbd99d'
down_revision = '0e394d611c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
